### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Its-Vichy** [Mewzax/RocketProxiesWrapper#1]
mec les ips sont whitelist, tu peux pas t'en servire pk tu veux les scrape, u pire fait un wrapper de l'api jsp

**Comment by Mewzax** [comment]
jsp j ai fait ça en 5 minutes et on m a demandé de le mettre sur github mais oe je vais l update parce que là c sacrément de la merde

**Comment by Mewzax** [comment]
> l'api

voila j ai fait un truc de merde :nez:

**Comment by Its-Vichy** [comment]
bah en soit non, mais moi je comptais faire un module avec des bails etc mais si ça pose pb jte le dirais

**Comment by Mewzax** [comment]
> bah en soit non, mais moi je comptais faire un module avec des bails etc mais si ça pose pb jte le dirais

tkt
